### PR TITLE
burrow util

### PR DESCRIPTION
**Pull request by fawwaz1234**
i'll add the burrow later

### CODE REVIEW

**Comment by fawwaz1234** [comment]
son of a bitch i hate java

**Comment by olliem5** [comment]
this is great code, i love the mcp mappings

**Comment by jakepriddle** [comment]
@fawwaz1234 did you test this code? Or did you just paste it in

**Comment by Gav06** [comment]
no, he programmed the entire burrow util with obfuscated mcp mappings

:)

**Comment by linustouchtips** [comment]
amazing, never seen better code

**Comment by fawwaz1234** [comment]
Sorry for what i caused

**Comment by yagel15637** [comment]
That doesn't change the fact you were gonna push this code here eventually - also, they're just mocking you lol, they don't actually care.

**Comment by fawwaz1234** [comment]
Push the code? Wait steal it?????

**Comment by jakepriddle** [comment]
why would u f*ck github
just delete your account, 
the ultimate middle finger

**Comment by Gav06** [comment]
harsh

**Pull request closed without merging**
